///////////////////////////////////////////////////////////////////////////////
// CppAdsClientServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CppAdsClient = 0x3F000000;
#define SRVNAME_CPPADSCLIENT "CppAdsClient"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CppAdsClientCAdsClientModule = {0xc1b71c44,0x4edf,0x4917,{0xb3,0x0c,0x53,0x97,0x78,0x7a,0x42,0x38}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_AdsClientModuleDefaultAdsPort = 0x00000001;
const PTCID PID_AdsClientModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_9D44425F_EB6F_4FA1_8E1B_F1D1FBF8609C_INCLUDED_)
#define _TC_TYPE_9D44425F_EB6F_4FA1_8E1B_F1D1FBF8609C_INCLUDED_
BEGIN_SCOPED_TYPED_ENUM(eAdsRpcState, SHORT)
 {
	Idle = 0,
	Init = 1,
	GetMethodHdl_Req = 2,
	GetMethodHdl_Res = 3,
	InvokeRpcMethod_Req = 4,
	InvokeRpcMethod_Res = 5,
	AdsError = 6
};
END_SCOPED_TYPED_ENUM(eAdsRpcState, SHORT)
#endif // !defined(_TC_TYPE_9D44425F_EB6F_4FA1_8E1B_F1D1FBF8609C_INCLUDED_)

#pragma pack(push,1)
typedef struct _AdsClientModuleInputs
{
	bool bReset;
} AdsClientModuleInputs, *PAdsClientModuleInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _AdsClientModuleOutputs
{
	eAdsRpcState AdsState;
	ULONGLONG AdsError;
} AdsClientModuleOutputs, *PAdsClientModuleOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_AdsClientModuleInputs 0
#define ADI_AdsClientModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
