///////////////////////////////////////////////////////////////////////////////
// CppAdsClientInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CppAdsClientServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
