///////////////////////////////////////////////////////////////////////////////
// CppAdsClientClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CppAdsClientClassFactory.h"
#include "CppAdsClientServices.h"
#include "CppAdsClientVersion.h"
#include "AdsClientModule.h"

BEGIN_CLASS_MAP(CCppAdsClientClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_CppAdsClient, CID_CppAdsClientCAdsClientModule, SRVNAME_CPPADSCLIENT "!CAdsClientModule", CAdsClientModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCppAdsClientClassFactory::CCppAdsClientClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_CPPADSCLIENT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CppAdsClient));
#endif //defined(TCDBG_UNIT_VERSION)
}

